In [11]:
import numpy as np
import matplotlib.pyplot as plt


In [12]:
ar1 = np.arange(-7,8)

ar1

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [13]:
ar2 = 3 * ar1

ar2

array([-21, -18, -15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12,  15,
        18,  21])

In [14]:
ar3 = ar1 / 4
ar4 = ar1 //4

print(f'ar3: {ar3}') 
print(f'ar4: {ar4}') 


ar3: [-1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.
  1.25  1.5   1.75]
ar4: [-2 -2 -2 -1 -1 -1 -1  0  0  0  0  1  1  1  1]


array([-8, -6, -4, -2,  0,  2,  4,  6,  8])